name = "QuestDB"
uuid = "c409e7dc-95dd-4f76-9030-daa6b84467ba"
version = "0.0.1"
authors = ["Brandon Escamilla <brandon.escamilla@outlook.com>"]

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
c_questdb_client_jll = "49a0df60-3d80-5428-85ce-5c0f24fd7b67"
